# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Print versions
      - name: Powershell Environment
        shell: pwsh
        run: |
          $PSVersionTable
      # Run tests
      - name: Run Pester
        shell: pwsh
        run: |
          $ProgressPreference='SilentlyContinue'
          Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser `
            -RequiredVersion 5.1.1 -Verbose
          Invoke-Pester $env:GITHUB_WORKSPACE -Output Detailed -CI
      # Run linter
      - name: Run Script Analyzer
        shell: pwsh
        run: |
          $ProgressPreference='SilentlyContinue'
          $ErrorActionPreference='Stop'
          Install-Module PSScriptAnalyzer -Force -SkipPublisherCheck -Scope CurrentUser `
            -RequiredVersion 1.19.1 -Verbose
          Invoke-ScriptAnalyzer -Path $env:GITHUB_WORKSPACE -Recurse -ReportSummary -EnableExit -ExcludeRule PSReviewUnusedParameter
